name: gas_stations_api

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=gasstations
    networks:
      - gas-stations-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - gas-stations-network
    restart: unless-stopped

  gas_stations_api:
    container_name: gas_stations_api
    build:
      dockerfile: Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_URL=jdbc:postgresql://postgres:5432/gasstations
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - gas-stations-network

networks:
  gas-stations-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: